// flow-typed signature: 27961657936c3323a6c32c274a302878
// flow-typed version: <<STUB>>/passport-saml_v^0.15.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-saml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-saml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-saml/lib/passport-saml/index' {
  declare module.exports: any;
}

declare module 'passport-saml/lib/passport-saml/inmemory-cache-provider' {
  declare module.exports: any;
}

declare module 'passport-saml/lib/passport-saml/saml' {
  declare module.exports: any;
}

declare module 'passport-saml/lib/passport-saml/strategy' {
  declare module.exports: any;
}

declare module 'passport-saml/test/samlTests' {
  declare module.exports: any;
}

declare module 'passport-saml/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-saml/lib/passport-saml/index.js' {
  declare module.exports: $Exports<'passport-saml/lib/passport-saml/index'>;
}
declare module 'passport-saml/lib/passport-saml/inmemory-cache-provider.js' {
  declare module.exports: $Exports<'passport-saml/lib/passport-saml/inmemory-cache-provider'>;
}
declare module 'passport-saml/lib/passport-saml/saml.js' {
  declare module.exports: $Exports<'passport-saml/lib/passport-saml/saml'>;
}
declare module 'passport-saml/lib/passport-saml/strategy.js' {
  declare module.exports: $Exports<'passport-saml/lib/passport-saml/strategy'>;
}
declare module 'passport-saml/test/samlTests.js' {
  declare module.exports: $Exports<'passport-saml/test/samlTests'>;
}
declare module 'passport-saml/test/tests.js' {
  declare module.exports: $Exports<'passport-saml/test/tests'>;
}
