// flow-typed signature: 4a8c59d1bce1a8fc68a65eb9440eafb8
// flow-typed version: <<STUB>>/passport-local-mongoose_v^4.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-local-mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-local-mongoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-local-mongoose/lib/errors' {
  declare module.exports: any;
}

declare module 'passport-local-mongoose/release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-local-mongoose/index' {
  declare module.exports: $Exports<'passport-local-mongoose'>;
}
declare module 'passport-local-mongoose/index.js' {
  declare module.exports: $Exports<'passport-local-mongoose'>;
}
declare module 'passport-local-mongoose/lib/errors.js' {
  declare module.exports: $Exports<'passport-local-mongoose/lib/errors'>;
}
declare module 'passport-local-mongoose/release.js' {
  declare module.exports: $Exports<'passport-local-mongoose/release'>;
}
