export const PRESS_RELEASES_REQUEST = 'PRESS_RELEASES_REQUEST';
export const PRESS_RELEASES_ERROR = 'PRESS_RELEASES_ERROR';
export const PRESS_RELEASES_SUCCESS = 'PRESS_RELEASES_SUCCESS';
export const PRESS_RELEASE_DELETE_SUCCESS = 'PRESS_RELEASE_DELETE_SUCCESS';
