import type { TOGGLE_FORM_TYPE, SET_FORM_OPTIONS_TYPE } from './flowTypes';

export const TOGGLE_FORM: TOGGLE_FORM_TYPE = 'ASSETS_PAGE/TOGGLE_FORM';
export const SET_FORM_OPTIONS: SET_FORM_OPTIONS_TYPE = 'ASSETS_PAGE/SET_FORM_OPTIONS';
