/* @flow */
import type {
  LOAD_DATA_INITIATION_TYPE,
  LOAD_DATA_SUCCESS_TYPE,
  LOAD_DATA_FAILURE_TYPE
} from './flowTypes';
export const LOAD_DATA_INITIATION: LOAD_DATA_INITIATION_TYPE = 'POSTFEEDITEM/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS: LOAD_DATA_SUCCESS_TYPE = 'POSTFEEDITEM/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE: LOAD_DATA_FAILURE_TYPE = 'POSTFEEDITEM/LOAD_DATA_FAILURE';
