/* @flow */
import type {
  SHOW_SECTION_FORM_TYPE,
  POST_SECTION_FORM_INPUT_TYPE
} from './flowTypes';
export const SHOW_SECTION_FORM: SHOW_SECTION_FORM_TYPE = 'DASHBOARD_POST_PAGE/SHOW_SECTION_FORM';
export const POST_SECTION_FORM_INPUT: POST_SECTION_FORM_INPUT_TYPE = 'DASHBOARD_POST_PAGE/POST_SECTION_FORM_INPUT';
