/* @flow */
import type {
  SHOW_SECTION_FORM_TYPE,
  POST_SECTION_FORM_INPUT_TYPE,
  POST_SECTION_FORM_RESET_TYPE,
  POST_SECTION_SET_MESSAGE_TYPE,
  POST_SECTION_CLEAR_MESSAGE_TYPE
} from './flowTypes';
export const SHOW_SECTION_FORM: SHOW_SECTION_FORM_TYPE =
  'DASHBOARD_POST_PAGE/SHOW_SECTION_FORM';
export const POST_SECTION_FORM_INPUT: POST_SECTION_FORM_INPUT_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_FORM_INPUT';
export const POST_SECTION_FORM_RESET: POST_SECTION_FORM_RESET_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_FORM_RESET';
export const POST_SECTION_SET_MESSAGE: POST_SECTION_SET_MESSAGE_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_SET_MESSAGE';
export const POST_SECTION_CLEAR_MESSAGE: POST_SECTION_CLEAR_MESSAGE_TYPE =
  'DASHBOARD_POST_PAGE/POST_SECTION_CLEAR_MESSAGE';
